admin_orders_index:
    path: /sell/orders/
    # POST is required because admin_order_index is also setup as the grid reset return route.
    methods: [GET,POST]
    defaults:
      _controller: 'Skaparate\Controller\Admin\CustomOrdersController::indexAction'
      _disable_module_prefix: true
