admin_orders_index:
    path: /sell/orders/
    methods: [GET,POST]
    defaults:
      _controller: 'Skaparate\Controller\Admin\CustomOrdersController::indexAction'
      _disable_module_prefix: true
